ICSharpCode.AvalonEdit/Editing/EditingCommandHandler.cs
This is a fix for #25.
The proposed change causes pasted tabs to be replaced with the number of spaces specified by **IndentationSize** when the **ConvertTabsToSpaces** option is enabled.
=> Added tab replacement to OnPaste in EditingCommandHandler

ICSharpCode.AvalonEdit/Editing/SelectionMouseHandler.cs
Selecting a word (double click) now causes the caret to move to the end of the selection. 
If selection is done backward (ctrl + mouse) the caret is moved to the start of the selection. 
Selecting the whole line (triple click) moves the caret to the end.
=> Fix #37 moving caret to start or end of selection

ICSharpCode.AvalonEdit/TextEditor.cs
Just a small thing... `TextEditor` has `Copy()`, `Cut()`, `Paste()` methods but not `Delete()` (which clears the selection without copying to the clipboard). 
I have a non WPF based app (that featured the old WinForm editor), with a context menu that has the "delete" item, and the only way to connect it is to have this ugly:
```C#
editor.SelectedText = ""; 
```
=> Added TextEditor.Delete()

ICSharpCode.AvalonEdit/Editing/CaretNavigationCommandHandler.cs
Fixes #40 when caret is at column 0, moving left doesn't go to previous line if virtual space is enabled.
=> Fix #40 cursor left should not go to prev line if virtual space

ICSharpCode.AvalonEdit/Indentation/DefaultIndentationStrategy.cs
Fixing a bug: the 2nd parameter of Replace is supposed to be the length of the text to replace (i.e. selection) instead of the length of the indentation string.
=> Fix parameter to Replace

ICSharpCode.AvalonEdit/Rendering/LinkElementGenerator.cs
This fixes issue #103 , it simply adds the same type of guard in MailLinkElementGenerator that LinkElementGenerator has prior to creating a URL (as what the regex thinks is valid may differ from what Uri class does).
=> Check for valid mail URL before creating

ICSharpCode.AvalonEdit/Editing/SelectionMouseHandler.cs
There may be times when SelectionMouseHandler detects a left mouse button down event on its TextArea, but then immediately the mouse capture is lost, and SelectionMouseHandler does not reset the selection mode. 
I noticed this when I started showing a dialog in response to my main window being activated, if I have detected that the file being edited by the user was changed by another process. When I activate my application by clicking on the editor, the SelectionMouseHandler detects this and begins selecting text. But immediately the TextArea loses mouse capture, as in my handler I show a modal dialog. When the user dismisses this dialog, even though the left mouse button is no longer pressed, moving the mouse around extends the selection as if it were.
I mimic exactly the approach in the …
=> Detect mouse capture loss during text selection

ICSharpCode.AvalonEdit/Folding/FoldingManager.cs
Issue is fixed by moving isFirstUpdate=false out of the foreach block, so that at the first update all sections get their folding state from the DefaultClosed property.
=> Fix only first fold is preserved when updating foldings

ICSharpCode.AvalonEdit/Editing/EditingCommandHandler.cs
Add null check for IndentationStrategy. If this is null (not common, but can legitimately be null), pressing Ctrl+I will crash.
=> Add null check in OnIndentSelection()

ICSharpCode.AvalonEdit/Search/SearchPanel.cs, ICSharpCode.AvalonEdit/Search/SearchPanel.xaml
I notice that if I press escape to close the search panel while the dropdown options panel is open, the latter remains open (actually, for me, it not only remains open, but jumps to the top of my screen).
=> Ensure search options panel is closed when search panel is closed

ICSharpCode.AvalonEdit/TextEditor.cs
Member textArea in TextEditor is readonly and set in ctors - it's never null. No need for null checks or access via the public property.
=> Minor cleanup

ICSharpCode.AvalonEdit/Search/SearchPanel.cs
How to reproduce?
1. Use the following xaml to custom `SearchPanel`.
2. Select any words then press `ctrl` + `f` to search first time.
3. Press `esc` or click close button of `SearchPanel` to close it.
4. Select any words then press `ctrl` + `f` again. Done, it throw `ArgumentNullException`.
```xaml
<avalonedit:TextEditor x:Name="PacTextEditor"
HorizontalScrollBarVisibility="Auto"
VerticalScrollBarVisibility="Auto"
ShowLineNumbers="True"
SyntaxHighlighting="JavaScript"
WordWrap="True"
... >
<avalonedit:TextEditor.Resources>
<Style TargetType="search:SearchPanel" 
BasedOn="{StaticResource {x:Type search:SearchPanel}}">
<Setter Property="Template">
<Setter.Value>
<ControlTemplate>
<Border Background="{DynamicResource WhiteBrush}"
BorderBrush="{DynamicResource TextBoxBorderBrush}" …
```
=> Fix ArgumentNullException issue.

ICSharpCode.AvalonEdit/Editing/EditingCommandHandler.cs
This fixes issues #22 and #57.
In `EditingCommandHandler.OnDelete` reuse the existing selection to make deleting a single character on multiple lines possible.
Also do not delete anything if the deletion would remove a line of a rectangular selection. This mimicks the behaviour of rectangular selections at the start or end of a line seen in Notepad++.
=> RectangleSelection does not handle backspace and delete key

ICSharpCode.AvalonEdit/Editing/TextAreaAutomationPeer.cs
Fix null-reference exception in TextAreaAutomationPeer - that was randomly occurring in the application.
=> Fix null-reference exception in TextAreaAutomationPeer

ICSharpCode.AvalonEdit/Folding/FoldingMarginMarker.cs
While investigating https://github.com/snoopwpf/snoopwpf/issues/28 i noticed that there is a missing null check in AvalonEdit.
The proposed change prevents that kind of issue.
=> Prevent null reference exception when rendering

ICSharpCode.AvalonEdit/Highlighting/Resources/TSQL-Mode.xshd
https://github.com/icsharpcode/AvalonEdit/issues/324
TSQL doesn't use \ as an escape character for strings.
=> Fix TSQL highlighting where a backslash exists before a single quote literal ('') in a string

ICSharpCode.AvalonEdit/Utils/TextFormatterFactory.cs
Now that .NET 4.6.2 is required (per f115e94d129b2485803281a3423ecd6f536fb9e9), here's a simple fix for the obsolete `FormattedText` constructor warning:
```
warning CS0618: 'FormattedText.FormattedText(string, CultureInfo, FlowDirection, Typeface, double, Brush, NumberSubstitution, TextFormattingMode)' is obsolete: 'Use the PixelsPerDip override'
```
I pass in PixelsPerDip using the recommendation from https://stackoverflow.com/a/45766452/1882616.
=> Fix PixelsPerDip warning (requires .NET 4.6.2+).

ICSharpCode.AvalonEdit.Tests/Highlighting/RichTextTests.cs, ICSharpCode.AvalonEdit/Highlighting/HighlightingColor.cs, ICSharpCode.AvalonEdit/Highlighting/HtmlRichTextWriter.cs, ICSharpCode.AvalonEdit/Utils/RichTextWriter.cs
`RichTextWriter.Write(RichText, int, int)` caused an immediate, unconditional StackOverflowException because it called the non-virtual `Write(RichText)` method due to RichText's implicit string conversion. I fixed this by invoking the virtual `Write(string)` method through a base TextWriter reference instead.
That revealed a bug in the derived class's virtual Write implementation. `HtmlRichTextWriter.Write(string)` incorrectly wrote the first char instead of the last/split char when ending the output. So, an input like "Oh, my!" would output as "Oh,Omy!".
Then I discovered that the `HighlightingColor.ToCss()` method omitted the background-color style because it ignored the `HighlightingColor.Background` property. I implemented that similar to the Foreground support.
I added the …
=> Fix RichText ToHtml stack overflow, corruption, and CSS.

.gitignore, ICSharpCode.AvalonEdit.Tests/Highlighting/HighlightingManagerTests.cs, ICSharpCode.AvalonEdit/Highlighting/HighlightingManager.cs
ILSpy changes themes by calling `HighlightingManager.RegisterHighlighting` to set the new color scheme: https://github.com/icsharpcode/ILSpy/blob/4ebe075e5859939463ae420446f024f10c3bf077/ILSpy/TextView/DecompilerTextView.cs#L1220-L1226
I noticed that each registered highlighting definition is added to the `HighlightingDefinitions` collection, and is never removed. Therefore, repeatedly changing the theme in ILSpy creates a small memory leak.
This PR changes this behavior so that registering a named highlighting definition will remove the previous one if it exists.
=> Overwrite registered highlightings

.gitignore, ICSharpCode.AvalonEdit.Tests/Highlighting/XmlHighlightingDefinitionTests.cs, ICSharpCode.AvalonEdit/Highlighting/Xshd/XmlHighlightingDefinition.cs
I noticed the following issue in ILSpy:
Note that `clt` is highlighted instead of `clt.un`.
This PR fixes this by making sure longer keywords are always preferred. Currently, this logic is only applied if every keyword in the list starts and ends with an alphanumeric character.
=> Prioritize longer keywords also when they're not alphanumeric

ICSharpCode.AvalonEdit/Editing/ImeNativeWrapper.cs
Unfortunately the built-in COM interop can't really be enabled for non-Windows platforms, we can't even stub `TF_CreateThreadMgr` on our side - .NET Runtime simply refused to call it.
This PR enables IME support for *nix platforms:
https://github.com/icsharpcode/AvalonEdit/assets/1067584/e68afb5b-1100-492f-890e-7a1eedebd35e
=> Add support for runtimes without built-in COM interop

ICSharpCode.AvalonEdit/Highlighting/Resources/Json.xshd
While doing https://github.com/icsharpcode/ILSpy/pull/3138 I noticed the JSON highlighting was wrong (see the last 2 lines in the screenshot), so this PR fixes that.
EDIT: I noticed there's an issue for this, so this fixes #410.
Here's the difference for the following example:
```json
{
"String": "Value",
"Bool": true,
"Null": null,
"Number:": -42e10,
"Object": {
"Foo:": "Bar",
"Multiline Key"
:
"Value"
},
"Array": ["Foo", "Bar", "Baz"]
}
```
Before:
After:
The rule for numbers adds support for `-` and reformats the regex.
I also kept the existing single-quoted strings and hex numbers which are not part of the JSON spec.
=> Fix JSON highlighting

ICSharpCode.AvalonEdit/Rendering/BackgroundGeometryBuilder.cs
An `AvaloniaEdit` user has discovered a problem with rectangular selection when virtual space is enabled. See https://github.com/AvaloniaUI/AvaloniaEdit/issues/472.
I provided a fix for `AvaloniaEdit`: https://github.com/AvaloniaUI/AvaloniaEdit/pull/496
`AvalonEdit` shows the same problem. This PR implements the fix for `AvalonEdit`.
Details: 
When a selection extends beyond the visual line into the "virtual space" then the `BackgroundGeometryBuilder` creates two segments per line. One for the visible text, and one for the virtual space.
The segment for the virtual space didn't apply the scroll offset. This is now fixed.
=> Fix: Rectangular selection ignores scroll offset
